// demo/lib/calculators-meta.ts
// Calculator metadata for the demo site (cleaned — no SEO competition data)

export type CalculatorType = "material" | "trade";

export interface CalculatorMeta {
  slug: string;
  title: string;
  shortDescription: string;
  category: string;
  type: CalculatorType;
  componentExport: string;
  lastUpdated: string;
  needsDisclaimer: boolean;
  needsSafetyWarning?: "plumbing" | "gas" | "electrical" | "structural";
  needsBrandDisclaimer?: string;
}

export const calculators: CalculatorMeta[] = [
  // ===== Material Calculators (/calculators/) =====
  {
    slug: "soffit-calculator",
    title: "Soffit Calculator",
    shortDescription: "Calculate soffit materials and vents for any roof.",
    category: "Roof",
    type: "material",
    componentExport: "SoffitCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "hardie-siding-calculator",
    title: "Hardie Board Siding Calculator",
    shortDescription: "Estimate James Hardie siding panels, trim, and cost.",
    category: "Siding & Drywall",
    type: "material",
    componentExport: "HardieSidingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
    needsBrandDisclaimer: "James Hardie Industries",
  },
  {
    slug: "house-repiping-cost-calculator",
    title: "House Repiping Cost Calculator",
    shortDescription: "Estimate whole-house repipe cost by pipe material.",
    category: "Plumbing",
    type: "material",
    componentExport: "HouseRepipingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
    needsSafetyWarning: "plumbing",
  },
  {
    slug: "epoxy-flooring-cost-calculator",
    title: "Epoxy Flooring Cost Calculator",
    shortDescription: "Estimate epoxy garage floor cost by square footage.",
    category: "Flooring",
    type: "material",
    componentExport: "EpoxyFlooringCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "concrete-driveway-cost-calculator",
    title: "Concrete Driveway Cost Calculator",
    shortDescription: "Estimate concrete driveway installation cost.",
    category: "Concrete & Asphalt",
    type: "material",
    componentExport: "ConcreteDrivewayCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "pressure-washing-estimate-calculator",
    title: "Pressure Washing Estimate Calculator",
    shortDescription: "Estimate pressure washing job cost by surface area.",
    category: "Landscape",
    type: "material",
    componentExport: "PressureWashingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "siding-calculator",
    title: "Siding Calculator",
    shortDescription: "Estimate siding cost across 6 materials.",
    category: "Siding & Drywall",
    type: "material",
    componentExport: "SidingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "spray-foam-insulation-cost-calculator",
    title: "Spray Foam Insulation Cost Calculator",
    shortDescription: "Estimate spray foam cost by board feet.",
    category: "Insulation",
    type: "material",
    componentExport: "SprayFoamInsulationCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "ductwork-replacement-cost-calculator",
    title: "Ductwork Replacement Cost Calculator",
    shortDescription: "Estimate HVAC ductwork replacement cost.",
    category: "HVAC",
    type: "material",
    componentExport: "DuctworkCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "heat-pump-cost-calculator",
    title: "Heat Pump Cost Calculator",
    shortDescription: "Estimate heat pump size and cost.",
    category: "HVAC",
    type: "material",
    componentExport: "HeatPumpCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "deck-footing-calculator",
    title: "Deck Footing Calculator",
    shortDescription: "Calculate deck footing count and depth.",
    category: "Deck & Fence",
    type: "material",
    componentExport: "DeckFootingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "deck-joist-span-calculator",
    title: "Deck Joist Span Calculator",
    shortDescription: "Calculate max joist span by size and spacing.",
    category: "Deck & Fence",
    type: "material",
    componentExport: "DeckJoistSpanCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "landscaping-cost-calculator",
    title: "Landscaping Cost Calculator",
    shortDescription: "Estimate landscaping cost by project type.",
    category: "Landscape",
    type: "material",
    componentExport: "LandscapingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "bathroom-remodel-cost-calculator",
    title: "Bathroom Remodel Cost Calculator",
    shortDescription: "Estimate bathroom remodel cost.",
    category: "Remodel",
    type: "material",
    componentExport: "BathroomRemodelCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "concrete-block-calculator",
    title: "Concrete Block Calculator",
    shortDescription: "Calculate CMU blocks needed for walls.",
    category: "Concrete & Asphalt",
    type: "material",
    componentExport: "ConcreteBlockCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "furnace-size-calculator",
    title: "Furnace Size Calculator",
    shortDescription: "Calculate furnace BTU by house size and climate.",
    category: "HVAC",
    type: "material",
    componentExport: "FurnaceSizeCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "drywall-calculator",
    title: "Drywall Calculator",
    shortDescription: "Calculate drywall sheets and materials needed.",
    category: "Siding & Drywall",
    type: "material",
    componentExport: "DrywallCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "roof-area-calculator",
    title: "Roof Area Calculator",
    shortDescription: "Calculate roof area from house dimensions and pitch.",
    category: "Roof",
    type: "material",
    componentExport: "RoofAreaCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "kitchen-remodel-cost-calculator",
    title: "Kitchen Remodel Cost Calculator",
    shortDescription: "Estimate kitchen remodel cost by layout and tier.",
    category: "Remodel",
    type: "material",
    componentExport: "KitchenRemodelCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "gutter-installation-cost-calculator",
    title: "Gutter Installation Cost Calculator",
    shortDescription: "Estimate gutter installation cost by material and length.",
    category: "Roof",
    type: "material",
    componentExport: "GutterCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "metal-roof-calculator",
    title: "Metal Roof Cost Calculator",
    shortDescription: "Estimate metal roof installation cost by type and area.",
    category: "Roof",
    type: "material",
    componentExport: "MetalRoofCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "paint-calculator",
    title: "Paint Calculator",
    shortDescription: "Calculate paint gallons and cost for any room.",
    category: "Siding & Drywall",
    type: "material",
    componentExport: "PaintCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "laminate-flooring-calculator",
    title: "Laminate Flooring Calculator",
    shortDescription: "Calculate cartons and cost for laminate flooring.",
    category: "Flooring",
    type: "material",
    componentExport: "LaminateFlooringCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "flooring-square-foot-calculator",
    title: "Flooring Square Foot Calculator",
    shortDescription: "Calculate square footage and cost across 6 flooring types.",
    category: "Flooring",
    type: "material",
    componentExport: "FlooringSquareFootCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "chain-link-fence-calculator",
    title: "Chain Link Fence Calculator",
    shortDescription: "Estimate chain link fence materials and installed cost.",
    category: "Deck & Fence",
    type: "material",
    componentExport: "ChainLinkFenceCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "gambrel-roof-calculator",
    title: "Gambrel Roof Calculator",
    shortDescription: "Calculate gambrel roof area, rafters, and cost.",
    category: "Roof",
    type: "material",
    componentExport: "GambrelRoofCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "mulch-calculator",
    title: "Mulch Calculator",
    shortDescription: "Calculate mulch cubic yards, bags, and cost for landscaping.",
    category: "Landscape",
    type: "material",
    componentExport: "MulchCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "gravel-calculator",
    title: "Gravel Calculator",
    shortDescription: "Calculate gravel cubic yards, tons, and cost for driveways.",
    category: "Concrete & Asphalt",
    type: "material",
    componentExport: "GravelCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "tile-calculator",
    title: "Tile Calculator",
    shortDescription: "Calculate tile count, boxes, and installed cost.",
    category: "Flooring",
    type: "material",
    componentExport: "TileCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "insulation-r-value-calculator",
    title: "Insulation R-Value Calculator",
    shortDescription: "Calculate recommended R-value, material, and cost by climate zone.",
    category: "Insulation",
    type: "material",
    componentExport: "InsulationRValueCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "deck-railing-spacing-calculator",
    title: "Deck Railing Spindle Spacing Calculator",
    shortDescription: "Calculate spindle count and code-compliant spacing.",
    category: "Deck & Fence",
    type: "material",
    componentExport: "DeckRailingSpacingCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "concrete-calculator",
    title: "Concrete Calculator",
    shortDescription: "Calculate cubic yards, bags, and cost for concrete.",
    category: "Concrete & Asphalt",
    type: "material",
    componentExport: "ConcreteCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "asphalt-calculator",
    title: "Asphalt Calculator",
    shortDescription: "Calculate tons, cubic yards, and cost for asphalt.",
    category: "Concrete & Asphalt",
    type: "material",
    componentExport: "AsphaltCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "carpet-calculator",
    title: "Carpet Calculator",
    shortDescription: "Calculate carpet square yards, padding, and installed cost.",
    category: "Flooring",
    type: "material",
    componentExport: "CarpetCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "wallpaper-calculator",
    title: "Wallpaper Calculator",
    shortDescription: "Calculate wallpaper rolls needed for any room.",
    category: "Siding & Drywall",
    type: "material",
    componentExport: "WallpaperCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },
  {
    slug: "deck-stair-calculator",
    title: "Deck Stair Calculator",
    shortDescription: "Calculate stair steps, stringers, and treads for decks.",
    category: "Deck & Fence",
    type: "material",
    componentExport: "DeckStairCalculator",
    lastUpdated: "2026-06-21",
    needsDisclaimer: true,
  },

  // ===== Trade Estimators (/tools/) =====
  {
    slug: "markup-calculator",
    title: "Markup Calculator",
    shortDescription: "Calculate markup, margin, and selling price from cost.",
    category: "Trade Estimating",
    type: "trade",
    componentExport: "MarkupCalculator",
    lastUpdated: "2026-05-14",
    needsDisclaimer: true,
  },
  {
    slug: "hvac-estimate-calculator",
    title: "HVAC Estimate Calculator",
    shortDescription: "Estimate HVAC installation costs by system type and tonnage.",
    category: "Trade Estimating",
    type: "trade",
    componentExport: "HVACEstimateCalculator",
    lastUpdated: "2026-05-14",
    needsDisclaimer: true,
  },
  {
    slug: "electrical-estimate-calculator",
    title: "Electrical Estimate Calculator",
    shortDescription: "Estimate electrical job costs by type and quantity.",
    category: "Trade Estimating",
    type: "trade",
    componentExport: "ElectricalEstimateCalculator",
    lastUpdated: "2026-05-14",
    needsDisclaimer: true,
    needsSafetyWarning: "electrical",
  },
  {
    slug: "plumbing-estimate-calculator",
    title: "Plumbing Estimate Calculator",
    shortDescription: "Estimate plumbing job costs by type and quantity.",
    category: "Trade Estimating",
    type: "trade",
    componentExport: "PlumbingEstimateCalculator",
    lastUpdated: "2026-05-14",
    needsDisclaimer: true,
    needsSafetyWarning: "plumbing",
  },
  {
    slug: "roofing-estimate-calculator",
    title: "Roofing Estimate Calculator",
    shortDescription: "Estimate roofing job costs by type and squares.",
    category: "Trade Estimating",
    type: "trade",
    componentExport: "RoofingEstimateCalculator",
    lastUpdated: "2026-05-14",
    needsDisclaimer: true,
    needsSafetyWarning: "structural",
  },
  {
    slug: "landscaping-estimate-calculator",
    title: "Landscaping Estimate Calculator",
    shortDescription: "Estimate landscaping job costs by type and quantity.",
    category: "Trade Estimating",
    type: "trade",
    componentExport: "LandscapingEstimateCalculator",
    lastUpdated: "2026-05-14",
    needsDisclaimer: true,
  },
];

export function getMaterialCalculators(): CalculatorMeta[] {
  return calculators.filter((c) => c.type === "material");
}

export function getTradeCalculators(): CalculatorMeta[] {
  return calculators.filter((c) => c.type === "trade");
}

export function getCalculatorBySlug(slug: string): CalculatorMeta | undefined {
  return calculators.find((c) => c.slug === slug);
}

export function getCalculatorsByCategory(): Record<string, CalculatorMeta[]> {
  const grouped: Record<string, CalculatorMeta[]> = {};
  for (const calc of calculators) {
    if (!grouped[calc.category]) grouped[calc.category] = [];
    grouped[calc.category].push(calc);
  }
  return grouped;
}
